#!/bin/bash
# chkconfig: 2345 80 20
# description: run levels 2,3,4,5.  start priority is 80.  stop priority is 20.
#
RETVAL=0;

start() {
  sudo su - nexus  
  /sbin/service nexus start
  exit $?     
}

stop() {
  sudo su - nexus  
  /sbin/service nexus stop
  exit $?	 
}

restart() {
        stop
        start
}

status() {
  sudo su - nexus  
  /sbin/service nexus restart
  exit $?
}

case "$1" in 
start)
        start
;;
stop)
        stop
;;
restart)
        restart
;;
status)
        status
;;

*)

echo $"Usage: $0 {start|stop|restart}"
exit 1
esac

exit $RETVAL 
